from setuptools import setup, find_packages

setup(
    name="sentinel2-yolo-aircraft",
    version="0.1.0",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "ultralytics>=8.1.0",
        "rasterio>=1.3.0",
        "numpy>=1.20.0",
        "opencv-python>=4.5.0",
        "shapely>=2.0.0",
        "geopandas>=0.12.0",
        "matplotlib>=3.5.0",
        "tqdm>=4.60.0",
        "pyproj>=3.0.0",
        "torch>=1.9.0",
        "torchvision>=0.10.0",
    ],
    include_package_data=True,
    description="Aircraft detection in Sentinel-2 satellite imagery using YOLO models",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Sentinel-2 YOLO Contributors",
    author_email="contact@example.com",
    url="https://github.com/yourusername/sentinel2-yolo-aircraft",
    license="MIT",
    extras_require={
        "dev": ["pytest>=7.0", "black>=22.0", "flake8>=4.0", "mypy>=0.9"],
        "onnx": ["onnx>=1.12.0", "onnxruntime>=1.13.0"],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: GIS",
    ],
)